<div class="clearfix"></div>
<div class="well span6">
    <div class="row">
        <div class="col-md-2 col-md-offset-2">
            <object width="720" height="1000" type="application/pdf" data="../../res/doc/CurriculumVitae-Steven_JALABERT.pdf?#zoom=85&scrollbar=0&toolbar=0&navpanes=0" id="pdf_content">
                <p><?php echo $this->translate('Votre navigateur n\'est pas compatible avec la visionneuse PDF.js, Vous pouvez toujours télécharger le PDF');?></p>
                <a href="../../res/doc/CurriculumVitae-Steven_JALABERT.pdf">
                    <img src="../../img/download_cv_green.png" alt="Download me!" height="35" width="170">
                </a>
            </object>
        </div>
    </div>
</div>