<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sSjServ%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('This web app is currently under construction, to learn more about myself, please proceed to my R&eacute;sum&eacute;')) ?></p>
    <p><a class="btn btn-lg btn-success" href="http://www.sjserv.fr/Cv"><?php echo $this->translate('Proceed to my R&eacute;sum&eacute;') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow My Code') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Put something about Github HERE.')) ?></p>
                <p><a class="btn btn-primary pull-right" href="https://github.com/stevenstrike" target="_blank"><?php echo $this->translate('My Github Repository') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Me') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Put something about Linkedin here.')) ?></p>
                <p><a class="btn btn-primary pull-right" href="https://fr.linkedin.com/in/steven-jalabert-89024a69"><?php echo $this->translate('My Linkedin') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Guides and finds') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Put something here about guides for servers,linux, neat apps.')) ?></p>
                <p><a class="btn btn-primary pull-right" href="#"><?php echo $this->translate('Guides & finds') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>